#!/bin/bash

[ ! -d "/run/namespace/" ] && mkdir /run/namespace/

conf="/etc/namespacehelper/namespacehelper.conf"

while IFS= read -r line
do
  if [ $(echo $line | cut -d " " -f 2) = "NET" ]
    then
     echo $(ip netns add $(echo $line | cut -d " " -f 4))
     echo $(ip link set dev $(echo $line | cut -d " " -f 6) netns $(echo $line | cut -d " " -f 4))
  else
    f="/run/namespace/$(echo $line | cut -d " " -f 4)"
    if [ ! -f $f ]
      then
        echo $(touch $f)
        echo $(unshare --$(echo $line | cut -d " " -f 2)=$f)
    fi
  fi
done < $conf
